algo = (input('Digite algo '))
print('Tipo: {}'.format(type(algo)))
print('Só tem espaco? {}'.format(algo.isspace))
print('É numero? {}'.format(algo.isnumeric()))
print('É alfabetico? {}'.format(algo.isalpha()))
print('É alfa numerico? {}'.format(algo.isalnum()))
print('Está em maiuscula? {}'.format(algo.isupper()))
print('Está em minuscula? {}'.format(algo.islower()))
print('Está capitalizada? {}'.format(algo.istitle()))
