frase = 'Curso em Video Python'
print(frase[2::2])
print(frase.count('o'))
print(frase.upper())
print(frase.lower())
print(frase.title())
print(frase.replace('Python', 'Chico'))
print('Curso' in frase)
div = frase.split()
print(div[0])